name: Build Cross-Platform Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Run PyInstaller
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then \
          pyinstaller gui.pyw --name YourApp --onefile --noconsole --add-data "assets;assets"; \
        else \
          pyinstaller gui.pyw --name YourApp --onefile --noconsole --add-data "assets:assets"; \
        fi

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: VideoPreviewGenerator-${{ matrix.os }}
        path: |
          dist/VideoPreviewGenerator*
