name: Build Cross-Platform Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Run PyInstaller
      run: |
        pyinstaller gui.pyw --name VideoPreviewGenerator --onefile --noconsole --add-data "assets{}assets".format(";" if runner.os == "Windows" else ":")

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: VideoPreviewGenerator-${{ matrix.os }}
        path: |
          dist/VideoPreviewGenerator*
